var searchData=
[
  ['basiclockable',['BasicLockable',['../d8/dcb/group___basic_lockable.html',1,'']]],
  ['basiclockable_2ehpp',['BasicLockable.hpp',['../df/d12/_basic_lockable_8hpp.html',1,'']]],
  ['block_5fallocator_5fdefault_5fblock_5falignment_5fv',['block_allocator_default_block_alignment_v',['../d0/dcd/_block_allocator_8hpp.html#a2d0ff49e4f7f39c7d122c52ddb8bd70d',1,'bit::memory']]],
  ['block_5fallocator_5fhas_5fdefault_5fblock_5falignment',['block_allocator_has_default_block_alignment',['../d3/d3b/structbit_1_1memory_1_1block__allocator__has__default__block__alignment.html',1,'bit::memory']]],
  ['block_5fallocator_5fhas_5finfo',['block_allocator_has_info',['../d1/d71/structbit_1_1memory_1_1block__allocator__has__info.html',1,'bit::memory']]],
  ['block_5fallocator_5fhas_5finfo_5fv',['block_allocator_has_info_v',['../d0/dcd/_block_allocator_8hpp.html#a97010fb5b16130383cec89fd72dd176f',1,'bit::memory']]],
  ['block_5fallocator_5fhas_5fnext_5fblock_5falignment',['block_allocator_has_next_block_alignment',['../d3/ddc/structbit_1_1memory_1_1block__allocator__has__next__block__alignment.html',1,'bit::memory']]],
  ['block_5fallocator_5fhas_5fnext_5fblock_5falignment_5fv',['block_allocator_has_next_block_alignment_v',['../d0/dcd/_block_allocator_8hpp.html#a14d65129a6368da80214d5e73ec85107',1,'bit::memory']]],
  ['block_5fallocator_5fhas_5fnext_5fblock_5fsize',['block_allocator_has_next_block_size',['../d0/d43/structbit_1_1memory_1_1block__allocator__has__next__block__size.html',1,'bit::memory']]],
  ['block_5fallocator_5fhas_5fnext_5fblock_5fsize_5fv',['block_allocator_has_next_block_size_v',['../d0/dcd/_block_allocator_8hpp.html#a51622a07afc558ae7d4039eed08c7bb4',1,'bit::memory']]],
  ['block_5fallocator_5ftagger',['block_allocator_tagger',['../dd/d50/classbit_1_1memory_1_1block__allocator__tagger.html',1,'bit::memory']]],
  ['block_5fallocator_5ftagger_2ehpp',['block_allocator_tagger.hpp',['../d2/d65/block__allocator__tagger_8hpp.html',1,'']]],
  ['block_5fallocator_5ftraits',['block_allocator_traits',['../d1/dc7/classbit_1_1memory_1_1block__allocator__traits.html',1,'bit::memory']]],
  ['block_5fallocator_5ftraits_2ehpp',['block_allocator_traits.hpp',['../d9/d89/block__allocator__traits_8hpp.html',1,'']]],
  ['block_5fallocator_5ftraits_3c_20allocator_5freference_3c_20blockallocator_20_3e_20_3e',['block_allocator_traits&lt; allocator_reference&lt; BlockAllocator &gt; &gt;',['../df/d6b/classbit_1_1memory_1_1block__allocator__traits_3_01allocator__reference_3_01_block_allocator_01_4_01_4.html',1,'bit::memory']]],
  ['blockallocator',['BlockAllocator',['../d0/d17/group___block_allocator.html',1,'']]],
  ['blockallocator_2ehpp',['BlockAllocator.hpp',['../d0/dcd/_block_allocator_8hpp.html',1,'']]],
  ['boundschecker',['BoundsChecker',['../d2/da2/group___bounds_checker.html',1,'']]],
  ['boundschecker_2ehpp',['BoundsChecker.hpp',['../dc/dd6/_bounds_checker_8hpp.html',1,'']]],
  ['buffer_5foverflow_5fhandler_5ft',['buffer_overflow_handler_t',['../df/d52/errors_8hpp.html#a0421e531060fafe1826e040bbd272277',1,'bit::memory']]],
  ['buffered_5fallocator',['buffered_allocator',['../d9/d37/classbit_1_1memory_1_1buffered__allocator.html',1,'bit::memory::buffered_allocator&lt; Allocator, Buffers &gt;'],['../d9/d37/classbit_1_1memory_1_1buffered__allocator.html#a58df1cd6551254e5cf45cc6e6c00893e',1,'bit::memory::buffered_allocator::buffered_allocator()']]],
  ['buffered_5fallocator_2ehpp',['buffered_allocator.hpp',['../de/d6d/buffered__allocator_8hpp.html',1,'']]],
  ['buffered_5fallocator_5fbase',['buffered_allocator_base',['../d5/dfd/classbit_1_1memory_1_1buffered__allocator__base.html',1,'bit::memory']]],
  ['buffered_5fallocator_5fbase_3c_20allocator_2c_20buffers_2c_20allocator_5ftraits_3c_20allocator_20_3e_3a_3ais_5fstateless_3a_3avalue_20_3e',['buffered_allocator_base&lt; Allocator, Buffers, allocator_traits&lt; Allocator &gt;::is_stateless::value &gt;',['../d5/dfd/classbit_1_1memory_1_1buffered__allocator__base.html',1,'bit::memory']]],
  ['buffered_5fallocator_5fbase_3c_20allocator_2c_20buffers_2c_20false_20_3e',['buffered_allocator_base&lt; Allocator, Buffers, false &gt;',['../d9/d93/classbit_1_1memory_1_1buffered__allocator__base_3_01_allocator_00_01_buffers_00_01false_01_4.html',1,'bit::memory']]],
  ['buffered_5fallocator_5fbase_3c_20allocator_2c_20buffers_2c_20true_20_3e',['buffered_allocator_base&lt; Allocator, Buffers, true &gt;',['../dd/d59/classbit_1_1memory_1_1buffered__allocator__base_3_01_allocator_00_01_buffers_00_01true_01_4.html',1,'bit::memory']]],
  ['bug_20list',['Bug List',['../de/da5/bug.html',1,'']]],
  ['bump_5fdown_5fallocator',['bump_down_allocator',['../d8/d39/classbit_1_1memory_1_1bump__down__allocator.html',1,'bit::memory::bump_down_allocator'],['../d8/d39/classbit_1_1memory_1_1bump__down__allocator.html#aa71cea443ac312ede540f9097d7c2f58',1,'bit::memory::bump_down_allocator::bump_down_allocator(memory_block block) noexcept'],['../d8/d39/classbit_1_1memory_1_1bump__down__allocator.html#a327c35fa16c21bde70bcf92054ee0d71',1,'bit::memory::bump_down_allocator::bump_down_allocator(bump_down_allocator &amp;&amp;other) noexcept=default']]],
  ['bump_5fdown_5fallocator_2ehpp',['bump_down_allocator.hpp',['../d4/db1/bump__down__allocator_8hpp.html',1,'']]],
  ['bump_5fdown_5flifo_5fallocator',['bump_down_lifo_allocator',['../de/d6e/classbit_1_1memory_1_1bump__down__lifo__allocator.html',1,'bit::memory::bump_down_lifo_allocator'],['../de/d6e/classbit_1_1memory_1_1bump__down__lifo__allocator.html#ae742a3562265cef437d68950975e58ce',1,'bit::memory::bump_down_lifo_allocator::bump_down_lifo_allocator(memory_block block) noexcept'],['../de/d6e/classbit_1_1memory_1_1bump__down__lifo__allocator.html#a47212dae6c6f7a23d2ced3cddc8f46da',1,'bit::memory::bump_down_lifo_allocator::bump_down_lifo_allocator(bump_down_lifo_allocator &amp;&amp;other) noexcept=default']]],
  ['bump_5fdown_5flifo_5fallocator_2ehpp',['bump_down_lifo_allocator.hpp',['../df/deb/bump__down__lifo__allocator_8hpp.html',1,'']]],
  ['bump_5fup_5fallocator',['bump_up_allocator',['../de/d5b/classbit_1_1memory_1_1bump__up__allocator.html',1,'bit::memory::bump_up_allocator'],['../de/d5b/classbit_1_1memory_1_1bump__up__allocator.html#a223c8465220ca7f2d1374144afc3a9ff',1,'bit::memory::bump_up_allocator::bump_up_allocator(memory_block block) noexcept'],['../de/d5b/classbit_1_1memory_1_1bump__up__allocator.html#abc43150e26a866d64df2700115dbb98d',1,'bit::memory::bump_up_allocator::bump_up_allocator(bump_up_allocator &amp;&amp;other) noexcept=default']]],
  ['bump_5fup_5fallocator_2ehpp',['bump_up_allocator.hpp',['../da/daa/bump__up__allocator_8hpp.html',1,'']]],
  ['bump_5fup_5flifo_5fallocator',['bump_up_lifo_allocator',['../dd/d0b/classbit_1_1memory_1_1bump__up__lifo__allocator.html',1,'bit::memory::bump_up_lifo_allocator'],['../dd/d0b/classbit_1_1memory_1_1bump__up__lifo__allocator.html#acb24c1e0d6de9652217761ab73379d70',1,'bit::memory::bump_up_lifo_allocator::bump_up_lifo_allocator(memory_block block) noexcept'],['../dd/d0b/classbit_1_1memory_1_1bump__up__lifo__allocator.html#a4598c07c6cc9af19242e7df2102a87d8',1,'bit::memory::bump_up_lifo_allocator::bump_up_lifo_allocator(bump_up_lifo_allocator &amp;&amp;other) noexcept=default']]],
  ['bump_5fup_5flifo_5fallocator_2ehpp',['bump_up_lifo_allocator.hpp',['../d1/dcc/bump__up__lifo__allocator_8hpp.html',1,'']]]
];
